[project]
name = "alarm-msg"
version = "0.1.0"
description = "Produce alarm-msg when specific person sends you a message"
authors = [
    { name = "PerchunPak", email = "git@perchun.it" }
]
requires-python = ">=3.14"
dependencies = ["discord-py-self"]

[project.scripts]
alarm-msg = "alarm_msg:main"

[build-system]
requires = ["uv_build>=0.9.0"]
build-backend = "uv_build"
